# Generated by Django 5.2.16 on 2026-07-24 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculums", "0012_acceptedanswer_unique_accepted_answer_per_question"),
        ("enrollments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonContentProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="not_started",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "watch_percentage",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Video watch progress (0-100). Ignored for non-video content.",
                        verbose_name="Watch Percentage",
                    ),
                ),
                (
                    "resume_position",
                    models.DurationField(
                        blank=True,
                        help_text="Playback position for video content.",
                        null=True,
                        verbose_name="Resume Position",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Started At"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed At"
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_records",
                        to="curriculums.lessoncontent",
                        verbose_name="Lesson Content",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_progress",
                        to="enrollments.enrollment",
                        verbose_name="Enrollment",
                    ),
                ),
            ],
            options={
                "ordering": ("enrollment", "content"),
                "indexes": [
                    models.Index(
                        fields=["enrollment"], name="enrollments_enrollm_1700c3_idx"
                    ),
                    models.Index(
                        fields=["content"], name="enrollments_content_0e13e4_idx"
                    ),
                    models.Index(
                        fields=["status"], name="enrollments_status_f4b1af_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("enrollment", "content"),
                        name="unique_content_progress_per_enrollment",
                    )
                ],
            },
        ),
    ]
