# Generated by Django 5.2.16 on 2026-07-24 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculums", "0012_acceptedanswer_unique_accepted_answer_per_question"),
        ("enrollments", "0002_lessoncontentprogress"),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="not_started",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "progress_percentage",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Overall completion percentage of the lesson (0-100).",
                        verbose_name="Progress Percentage",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Started At"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed At"
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_progress",
                        to="enrollments.enrollment",
                        verbose_name="Enrollment",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_records",
                        to="curriculums.lesson",
                        verbose_name="Lesson",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lesson Progress",
                "verbose_name_plural": "Lesson Progress",
                "ordering": ("enrollment", "lesson"),
                "indexes": [
                    models.Index(
                        fields=["enrollment"], name="enrollments_enrollm_a82816_idx"
                    ),
                    models.Index(
                        fields=["lesson"], name="enrollments_lesson__6b93a2_idx"
                    ),
                    models.Index(
                        fields=["status"], name="enrollments_status_a7c19c_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("enrollment", "lesson"),
                        name="unique_lesson_progress_per_enrollment",
                    )
                ],
            },
        ),
    ]
