# Generated by Django 5.2.16 on 2026-07-24 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0007_remove_course_instructors_coursecollaborator_and_more"),
        ("enrollments", "0004_sectionprogress"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="not_started",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "progress_percentage",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Overall completion percentage of the course (0-100).",
                        verbose_name="Progress Percentage",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Started At"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed At"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_records",
                        to="courses.course",
                        verbose_name="Course",
                    ),
                ),
                (
                    "enrollment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_progress",
                        to="enrollments.enrollment",
                        verbose_name="Enrollment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Progress",
                "verbose_name_plural": "Course Progress",
                "ordering": ("course", "enrollment"),
                "indexes": [
                    models.Index(
                        fields=["course"], name="enrollments_course__6cac6c_idx"
                    ),
                    models.Index(
                        fields=["status"], name="enrollments_status_082402_idx"
                    ),
                ],
            },
        ),
    ]
