# Generated by Django 5.2.16 on 2026-08-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enrollments", "0005_courseprogress"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="last_activity_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="Last activity at"
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="started_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Started at"
            ),
        ),
    ]
