# Generated by Django 5.2.16 on 2026-08-02 19:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculums", "0023_alter_attachment_title"),
        ("enrollments", "0006_enrollment_last_activity_at_enrollment_started_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lessoncontentprogress",
            options={
                "ordering": ("enrollment", "content"),
                "verbose_name": "Lesson Content Progress",
                "verbose_name_plural": "Lesson Content Progress",
            },
        ),
        migrations.RemoveIndex(
            model_name="lessoncontentprogress",
            name="enrollments_enrollm_1700c3_idx",
        ),
        migrations.RemoveIndex(
            model_name="lessoncontentprogress",
            name="enrollments_content_0e13e4_idx",
        ),
        migrations.RemoveIndex(
            model_name="lessoncontentprogress",
            name="enrollments_status_f4b1af_idx",
        ),
        migrations.RemoveField(
            model_name="lessoncontentprogress",
            name="resume_position",
        ),
        migrations.RemoveField(
            model_name="lessoncontentprogress",
            name="watch_percentage",
        ),
        migrations.RemoveField(
            model_name="lessonprogress",
            name="progress_percentage",
        ),
        migrations.AddField(
            model_name="enrollment",
            name="progress",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Overall completion percentage of the course (0-100).",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Progress Percentage",
            ),
        ),
        migrations.AddField(
            model_name="lessonprogress",
            name="progress",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Overall completion percentage of the lesson (0-100).",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Progress Percentage",
            ),
        ),
        migrations.AlterField(
            model_name="lessoncontentprogress",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not Started"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                ],
                db_index=True,
                default="not_started",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AddIndex(
            model_name="lessoncontentprogress",
            index=models.Index(
                fields=["enrollment", "status"], name="enrollments_enrollm_1b4a24_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lessoncontentprogress",
            index=models.Index(
                fields=["content", "status"], name="enrollments_content_8823cf_idx"
            ),
        ),
    ]
