# Generated by Django 5.2.16 on 2026-08-12 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enrollments", "0007_alter_lessoncontentprogress_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "watched_seconds",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total watched video time in seconds.",
                        verbose_name="Watched Seconds",
                    ),
                ),
                (
                    "lesson_content_progress",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_progress",
                        to="enrollments.lessoncontentprogress",
                        verbose_name="Lesson Content Progress",
                    ),
                ),
            ],
            options={
                "verbose_name": "Video Progress",
                "verbose_name_plural": "Video Progress",
            },
        ),
    ]
