# Generated by Django 5.2.16 on 2026-08-12 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculums", "0026_remove_lesson_completion_criteria_and_more"),
        ("enrollments", "0008_videoprogress"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseLessonBookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to="enrollments.enrollment",
                        verbose_name="Enrollment",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to="curriculums.lesson",
                        verbose_name="Lesson",
                    ),
                ),
            ],
        ),
    ]
