# Generated by Django 5.2.16 on 2026-08-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enrollments", "0009_courselessonbookmark"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("suspended", "Suspended"),
                    ("pending", "Pending"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
