# Generated by Django 5.2.16 on 2026-08-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enrollments", "0010_alter_enrollment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
