# Generated by Django 5.2.16 on 2026-08-29 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enrollments", "0011_enrollment_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoWatchEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("watched_seconds", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "video_progress",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watch_events",
                        to="enrollments.videoprogress",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="enrollments_created_ce56c8_idx"
                    )
                ],
            },
        ),
    ]
