# Generated by Django 5.2.16 on 2026-09-09 21:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("enrollments", "0012_videowatchevent"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CourseProgress",
        ),
    ]
