# Generated by Django 5.2.16 on 2026-09-09 21:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("enrollments", "0013_delete_courseprogress"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SectionProgress",
        ),
    ]
