# Generated by Django 5.2.16 on 2026-08-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="stripe_event_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
