# Generated by Django 5.2.16 on 2026-08-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0002_payment_stripe_event_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="stripe_checkout_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
