# Generated by Django 5.2.16 on 2026-07-09 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, upload_to="avatars/", verbose_name="Avatar"
                    ),
                ),
                ("biography", models.TextField(blank=True, verbose_name="Biography")),
                (
                    "headline",
                    models.CharField(
                        blank=True,
                        help_text="Short professional summary",
                        max_length=255,
                        verbose_name="Headline",
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="Website")),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Country"
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Timezone"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Language"
                    ),
                ),
                ("linkedin", models.URLField(blank=True, verbose_name="Linkedin")),
                ("github", models.URLField(blank=True, verbose_name="Github")),
                (
                    "date_of_birth",
                    models.DateField(blank=True, null=True, verbose_name="Birthday"),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Company"
                    ),
                ),
                (
                    "job_title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Job Title"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "ordering": ["user"],
            },
        ),
    ]
