# Generated by Django 5.2.16 on 2026-07-09 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstructorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "professional_title",
                    models.CharField(max_length=255, verbose_name="Professional Title"),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Organization"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Is Verified"),
                ),
                (
                    "introduction_video",
                    models.FileField(
                        blank=True,
                        upload_to="instructors/introduction_videos/",
                        verbose_name="Introduction Video",
                    ),
                ),
                (
                    "years_of_experience",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Years of Experience"
                    ),
                ),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instructor_profile",
                        to="profiles.profile",
                        verbose_name="Profile",
                    ),
                ),
            ],
            options={
                "ordering": ["profile__user__username"],
                "indexes": [
                    models.Index(
                        fields=["is_verified"], name="profiles_in_is_veri_84bc9e_idx"
                    ),
                    models.Index(
                        fields=["years_of_experience"],
                        name="profiles_in_years_o_abd544_idx",
                    ),
                ],
            },
        ),
    ]
