# Generated by Django 5.2.16 on 2026-07-09 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_instructorprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "learning_goal",
                    models.CharField(
                        blank=True,
                        help_text="Student's primary learning objective.",
                        max_length=255,
                    ),
                ),
                (
                    "current_streak",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Current Streak"
                    ),
                ),
                (
                    "longest_streak",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Longest Streak"
                    ),
                ),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_profile",
                        to="profiles.profile",
                        verbose_name="Profile",
                    ),
                ),
            ],
            options={
                "ordering": ["profile__user__username"],
            },
        ),
    ]
