# Generated by Django 5.2.16 on 2026-07-10 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0004_skill"),
    ]

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "institution",
                    models.CharField(max_length=255, verbose_name="Institution"),
                ),
                ("degree", models.CharField(max_length=255, verbose_name="Degree")),
                (
                    "field_of_study",
                    models.CharField(max_length=255, verbose_name="Field Of Study"),
                ),
                (
                    "start_year",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Start Year"
                    ),
                ),
                (
                    "end_year",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Leave blank if currently studying.",
                        null=True,
                        verbose_name="End Year",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education",
                        to="profiles.profile",
                        verbose_name="Profile",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_year", "-end_year", "institution"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("end_year__isnull", True),
                            ("end_year__gte", models.F("start_year")),
                            _connector="OR",
                        ),
                        name="education_end_year_gte_start_year",
                    )
                ],
            },
        ),
    ]
