# Generated by Django 5.2.16 on 2026-07-10 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0005_education"),
    ]

    operations = [
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=255, verbose_name="Company")),
                ("position", models.CharField(max_length=255, verbose_name="Position")),
                ("start_date", models.DateField(verbose_name="Start Date")),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Leave blank if this is the current position.",
                        null=True,
                        verbose_name="End Date",
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(default=False, verbose_name="Current Position"),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiences",
                        to="profiles.profile",
                        verbose_name="Profile",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date", "-end_date", "company"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("end_date__isnull", True),
                            ("end_date__gte", models.F("start_date")),
                            _connector="OR",
                        ),
                        name="experience_end_date_gte_start_date",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("is_current", False),
                            ("end_date__isnull", True),
                            _connector="OR",
                        ),
                        name="experience_current_requires_null_end_date",
                    ),
                ],
            },
        ),
    ]
