# Generated by Django 5.2.16 on 2026-07-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0007_sociallink"),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.TextField(max_length=250, verbose_name="Language")),
                (
                    "proficiency",
                    models.CharField(
                        choices=[
                            ("native", "Native"),
                            ("c2", "Proficient"),
                            ("c1", "Advanced"),
                            ("B2", "Upper Intermediate"),
                            ("B1", "Intermediate"),
                            ("A2", "Elementary"),
                            ("A1", "Beginner"),
                        ],
                        max_length=6,
                        verbose_name="Proficiency",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="education",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="experience",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="experience",
            name="location",
            field=models.CharField(blank=True, max_length=250, verbose_name="Location"),
        ),
        migrations.AddField(
            model_name="profile",
            name="cover",
            field=models.ImageField(
                blank=True, upload_to="covers/", verbose_name="Cover"
            ),
        ),
    ]
