# Generated by Django 5.2.16 on 2026-07-21 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0009_language_profile"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="skill",
            name="profiles_sk_name_1f6740_idx",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="profiles",
        ),
        migrations.AddField(
            model_name="skill",
            name="profile",
            field=models.ForeignKey(
                default=5,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skills",
                to="profiles.profile",
                verbose_name="Profile",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="education",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="educations",
                to="profiles.profile",
                verbose_name="Profile",
            ),
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(
                fields=["name", "profile"], name="profiles_sk_name_97f94d_idx"
            ),
        ),
    ]
