# Generated by Django 5.2.16 on 2026-07-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0010_remove_skill_profiles_sk_name_1f6740_idx_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="education",
            options={"ordering": ["-start_date", "-end_date", "institution"]},
        ),
        migrations.RemoveConstraint(
            model_name="education",
            name="education_end_year_gte_start_year",
        ),
        migrations.RemoveField(
            model_name="education",
            name="end_year",
        ),
        migrations.RemoveField(
            model_name="education",
            name="start_year",
        ),
        migrations.AddField(
            model_name="education",
            name="end_date",
            field=models.DateField(
                blank=True,
                help_text="Leave blank if currently studying.",
                null=True,
                verbose_name="End Year",
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="Start Date"),
        ),
        migrations.AddConstraint(
            model_name="education",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("end_date__isnull", True),
                    ("end_date__gte", models.F("start_date")),
                    _connector="OR",
                ),
                name="education_end_date_gte_start_date",
            ),
        ),
    ]
