# Generated by Django 5.2.16 on 2026-07-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0011_alter_education_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="language",
            name="proficiency",
            field=models.CharField(
                choices=[
                    ("Native", "Native"),
                    ("C2", "Proficient"),
                    ("C1", "Advanced"),
                    ("B2", "Upper Intermediate"),
                    ("B1", "Intermediate"),
                    ("A2", "Elementary"),
                    ("A1", "Beginner"),
                ],
                max_length=6,
                verbose_name="Proficiency",
            ),
        ),
    ]
