# Generated by Django 5.2.16 on 2026-07-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0012_alter_language_proficiency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="start_date",
            field=models.DateField(blank=True, verbose_name="Start Date"),
        ),
    ]
