# Generated by Django 5.2.16 on 2026-08-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0014_alter_experience_start_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sociallink",
            name="url",
        ),
        migrations.AddField(
            model_name="sociallink",
            name="address",
            field=models.URLField(default="https://google.com", verbose_name="Address"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sociallink",
            name="platform",
            field=models.CharField(
                choices=[
                    ("telegram", "Telegram"),
                    ("instagram", "Instagram"),
                    ("twitter", "Twitter"),
                    ("linkedin", "LinkedIn"),
                    ("youtube", "YouTube"),
                    ("github", "GitHub"),
                    ("facebook", "Facebook"),
                    ("email", "Email"),
                ],
                max_length=20,
                verbose_name="Platform",
            ),
        ),
    ]
