# Generated by Django 5.2.16 on 2026-08-25 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0015_remove_sociallink_url_sociallink_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="instructorprofile",
            name="application_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="instructorprofile",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="instructorprofile",
            name="resume",
            field=models.FileField(blank=True, upload_to="instructors/resumes/"),
        ),
        migrations.AddField(
            model_name="instructorprofile",
            name="verification_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="instructorprofile",
            name="introduction_video",
            field=models.FileField(blank=True, upload_to="instructors/videos/"),
        ),
        migrations.AlterField(
            model_name="instructorprofile",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="instructorprofile",
            name="profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instructor_profile",
                to="profiles.profile",
            ),
        ),
        migrations.AlterField(
            model_name="instructorprofile",
            name="years_of_experience",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
