# Generated by Django 5.2.16 on 2026-08-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0016_instructorprofile_application_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="biography",
        ),
        migrations.AddField(
            model_name="instructorprofile",
            name="biography",
            field=models.TextField(blank=True, verbose_name="Instructor Biography"),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="biography",
            field=models.TextField(blank=True, verbose_name="Instructor Biography"),
        ),
    ]
