# Generated by Django 5.2.16 on 2026-08-25 11:09

from django.db import migrations, models

import profiles.models


class Migration(migrations.Migration):
    dependencies = [
        (
            "profiles",
            "0017_remove_profile_biography_instructorprofile_biography_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="avatar",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="cover",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="headline",
        ),
        migrations.AddField(
            model_name="instructorprofile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                upload_to=profiles.models.profile_image_upload_to,
                verbose_name="Avatar",
            ),
        ),
        migrations.AddField(
            model_name="instructorprofile",
            name="cover",
            field=models.ImageField(
                blank=True,
                upload_to=profiles.models.profile_image_upload_to,
                verbose_name="Cover",
            ),
        ),
        migrations.AddField(
            model_name="instructorprofile",
            name="headline",
            field=models.CharField(
                blank=True,
                help_text="Short professional summary",
                max_length=255,
                verbose_name="Headline",
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                upload_to=profiles.models.profile_image_upload_to,
                verbose_name="Avatar",
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="cover",
            field=models.ImageField(
                blank=True,
                upload_to=profiles.models.profile_image_upload_to,
                verbose_name="Cover",
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="headline",
            field=models.CharField(
                blank=True,
                help_text="Short professional summary",
                max_length=255,
                verbose_name="Headline",
            ),
        ),
    ]
