# Generated by Django 5.2.16 on 2026-08-25 11:19

from django.db import migrations, models

import profiles.models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0018_remove_profile_avatar_remove_profile_cover_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instructorprofile",
            name="avatar",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="avatar",
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                upload_to=profiles.models.profile_image_upload_to,
                verbose_name="Avatar",
            ),
        ),
    ]
