# Generated by Django 5.2.16 on 2026-08-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0019_remove_instructorprofile_avatar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instructorprofile",
            name="introduction_video",
            field=models.URLField(blank=True),
        ),
    ]
