# Generated by Django 5.2.16 on 2026-07-24 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("curriculums", "0014_delete_acceptedanswer_delete_choice_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "instructions",
                    models.TextField(blank=True, verbose_name="Instructions"),
                ),
                (
                    "passing_score",
                    models.PositiveSmallIntegerField(
                        default=70,
                        help_text="Required score (0-100) to pass.",
                        verbose_name="Passing Score (%)",
                    ),
                ),
                (
                    "time_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Leave empty for unlimited time.",
                        null=True,
                        verbose_name="Time Limit (minutes)",
                    ),
                ),
                (
                    "max_attempts",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Set to 0 for unlimited attempts.",
                        verbose_name="Maximum Attempts",
                    ),
                ),
                (
                    "shuffle_questions",
                    models.BooleanField(
                        default=False, verbose_name="Shuffle Questions"
                    ),
                ),
                (
                    "shuffle_choices",
                    models.BooleanField(default=False, verbose_name="Shuffle Choices"),
                ),
                (
                    "show_correct_answers",
                    models.BooleanField(
                        default=True, verbose_name="Show Correct Answers"
                    ),
                ),
                (
                    "content",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz",
                        to="curriculums.lessoncontent",
                        verbose_name="Lesson Content",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz Content",
                "verbose_name_plural": "Quiz Contents",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("single_choice", "Single Choice"),
                            ("multiple_choice", "Multiple Choice"),
                            ("true_false", "True / False"),
                            ("short_answer", "Short Answer"),
                        ],
                        default="single_choice",
                        max_length=30,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        help_text="Difficulty level of the question.",
                        max_length=10,
                        verbose_name="Difficulty",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField()),
                ("points", models.PositiveSmallIntegerField(default=1)),
                ("explanation", models.TextField(blank=True)),
                ("is_required", models.BooleanField(default=True)),
                (
                    "estimated_time",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Estimated time to answer in seconds.",
                        null=True,
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="assessments.quizcontent",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=500)),
                ("is_correct", models.BooleanField(default=False)),
                ("order", models.PositiveSmallIntegerField()),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="assessments.question",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("question", "order"),
                        name="unique_choice_order_per_question",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AcceptedAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.CharField(max_length=255)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accepted_answers",
                        to="assessments.question",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("question", "answer"),
                        name="unique_accepted_answer_per_question",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["quiz"], name="assessments_quiz_id_95893e_idx"),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["order"], name="assessments_order_c2c3d3_idx"),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["difficulty"], name="assessments_difficu_f7cef9_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.UniqueConstraint(
                fields=("quiz", "order"), name="unique_question_order_per_quiz"
            ),
        ),
    ]
