# Generated by Django 5.2.16 on 2026-07-24 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessments", "0001_initial"),
        ("enrollments", "0005_courseprogress"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempt_number",
                    models.PositiveSmallIntegerField(verbose_name="Attempt Number"),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Quiz score as a percentage (0-100).",
                        max_digits=5,
                        verbose_name="Score (%)",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Started At"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Submitted At"
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_attempts",
                        to="enrollments.enrollment",
                        verbose_name="Enrollment",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="assessments.quizcontent",
                        verbose_name="Quiz",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz Attempt",
                "verbose_name_plural": "Quiz Attempts",
                "ordering": ("-started_at",),
                "indexes": [
                    models.Index(
                        fields=["enrollment"], name="assessments_enrollm_44b770_idx"
                    ),
                    models.Index(
                        fields=["quiz"], name="assessments_quiz_id_12b100_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("quiz", "enrollment", "attempt_number"),
                        name="unique_attempt_number_per_enrollment",
                    )
                ],
            },
        ),
    ]
