# Generated by Django 5.2.16 on 2026-07-24 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessments", "0002_quizattempt"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text_answer",
                    models.TextField(
                        blank=True,
                        help_text="Student's answer for short-answer questions.",
                        verbose_name="Text Answer",
                    ),
                ),
                (
                    "score_awarded",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Score Awarded",
                    ),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="assessments.quizattempt",
                        verbose_name="Quiz Attempt",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="assessments.question",
                        verbose_name="Question",
                    ),
                ),
                (
                    "selected_choices",
                    models.ManyToManyField(
                        blank=True,
                        related_name="quiz_answers",
                        to="assessments.choice",
                        verbose_name="Selected Choices",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz Answer",
                "verbose_name_plural": "Quiz Answers",
                "ordering": ("attempt", "question__order"),
                "indexes": [
                    models.Index(
                        fields=["attempt"], name="assessments_attempt_b784b3_idx"
                    ),
                    models.Index(
                        fields=["question"], name="assessments_questio_060b47_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("attempt", "question"),
                        name="unique_question_answer_per_attempt",
                    )
                ],
            },
        ),
    ]
