# Generated by Django 5.2.16 on 2026-07-24 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessments", "0003_quizanswer"),
        ("curriculums", "0014_delete_acceptedanswer_delete_choice_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instructions", models.TextField(verbose_name="Instructions")),
                (
                    "max_score",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="Maximum Score"
                    ),
                ),
                (
                    "due_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Due Date"
                    ),
                ),
                (
                    "allow_late_submission",
                    models.BooleanField(
                        default=False, verbose_name="Allow Late Submission"
                    ),
                ),
                (
                    "max_attempts",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Set to 0 for unlimited attempts.",
                        verbose_name="Maximum Attempts",
                    ),
                ),
                (
                    "accepted_file_types",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated list (e.g. pdf,docx,zip). Leave blank to allow any.",
                        max_length=255,
                        verbose_name="Accepted File Types",
                    ),
                ),
                (
                    "max_file_size_mb",
                    models.PositiveSmallIntegerField(
                        default=50, verbose_name="Maximum File Size (MB)"
                    ),
                ),
                (
                    "content",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment",
                        to="curriculums.lessoncontent",
                        verbose_name="Lesson Content",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assignment",
                "verbose_name_plural": "Assignments",
            },
        ),
    ]
