# Generated by Django 5.2.16 on 2026-07-24 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessments", "0004_assignment"),
        ("enrollments", "0005_courseprogress"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignmentSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempt_number",
                    models.PositiveSmallIntegerField(verbose_name="Attempt Number"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("graded", "Graded"),
                            ("returned", "Returned"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "submission_text",
                    models.TextField(
                        blank=True,
                        help_text="Optional written submission.",
                        verbose_name="Submission Text",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Score",
                    ),
                ),
                ("feedback", models.TextField(blank=True, verbose_name="Feedback")),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Started At"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Submitted At"
                    ),
                ),
                (
                    "graded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Graded At"
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="assessments.assignment",
                        verbose_name="Assignment",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment_submissions",
                        to="enrollments.enrollment",
                        verbose_name="Enrollment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assignment Submission",
                "verbose_name_plural": "Assignment Submissions",
                "ordering": ("-submitted_at", "-started_at"),
                "indexes": [
                    models.Index(
                        fields=["assignment"], name="assessments_assignm_75872b_idx"
                    ),
                    models.Index(
                        fields=["enrollment"], name="assessments_enrollm_bfb234_idx"
                    ),
                    models.Index(
                        fields=["status"], name="assessments_status_02e17d_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("assignment", "enrollment", "attempt_number"),
                        name="unique_assignment_attempt_per_enrollment",
                    )
                ],
            },
        ),
    ]
