# Generated by Django 5.2.16 on 2026-07-24 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessments", "0005_assignmentsubmission"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignmentSubmissionFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="assignments/submissions/", verbose_name="File"
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="Original Filename"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Uploaded At"),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="assessments.assignmentsubmission",
                        verbose_name="Submission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assignment Submission File",
                "verbose_name_plural": "Assignment Submission Files",
                "ordering": ("uploaded_at",),
                "indexes": [
                    models.Index(
                        fields=["submission"], name="assessments_submiss_3c0738_idx"
                    )
                ],
            },
        ),
    ]
