# Generated by Django 5.2.16 on 2026-07-30 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessments", "0006_assignmentsubmissionfile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="estimated_time",
            field=models.DurationField(
                blank=True, help_text="Estimated time to answer.", null=True
            ),
        ),
        migrations.CreateModel(
            name="BooleanAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.BooleanField(default=False)),
                (
                    "question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boolean_answers",
                        to="assessments.question",
                    ),
                ),
            ],
        ),
    ]
