# Generated by Django 5.2.16 on 2026-08-03 15:53

from django.db import migrations, models

import assessments.models.assignment_submission


class Migration(migrations.Migration):
    dependencies = [
        ("assessments", "0007_alter_question_estimated_time_booleananswer"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentsubmission",
            name="submission_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=assessments.models.assignment_submission.assignment_submission_upload_path,
                verbose_name="Submission File",
            ),
        ),
    ]
