# Generated by Django 5.2.16 on 2026-08-03 17:13

from django.db import migrations, models

import assessments.models.assignment_submission


class Migration(migrations.Migration):
    dependencies = [
        ("assessments", "0008_assignmentsubmission_submission_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignmentsubmission",
            name="submission_file",
        ),
        migrations.AlterField(
            model_name="assignmentsubmissionfile",
            name="file",
            field=models.FileField(
                upload_to=assessments.models.assignment_submission.assignment_submission_upload_path,
                verbose_name="File",
            ),
        ),
    ]
