# Generated by Django 5.2.16 on 2026-08-03 17:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assessments", "0009_remove_assignmentsubmission_submission_file_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assignmentsubmission",
            options={
                "ordering": ("-submitted_at",),
                "verbose_name": "Assignment Submission",
                "verbose_name_plural": "Assignment Submissions",
            },
        ),
        migrations.RemoveField(
            model_name="assignmentsubmission",
            name="started_at",
        ),
    ]
