# Generated by Django 5.2.16 on 2026-08-03 17:31

from django.db import migrations, models

import assessments.models.assignment_submission


class Migration(migrations.Migration):
    dependencies = [
        ("assessments", "0010_alter_assignmentsubmission_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignmentsubmissionfile",
            name="file",
            field=models.FileField(
                max_length=255,
                upload_to=assessments.models.assignment_submission.assignment_submission_upload_path,
                verbose_name="File",
            ),
        ),
    ]
