# Generated by Django 5.2.16 on 2026-08-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessments", "0011_alter_assignmentsubmissionfile_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentsubmission",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("graded", "Graded"),
                    ("returned", "Returned"),
                    ("late", "Late"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
