# Generated by Django 5.2.16 on 2026-08-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessments", "0012_assignmentsubmission_updated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizanswer",
            name="bool_answer",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
