# Generated by Django 5.2.16 on 2026-08-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessments", "0013_quizanswer_bool_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentsubmissionfile",
            name="size",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
