# Generated by Django 5.2.16 on 2026-08-15 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessments", "0014_assignmentsubmissionfile_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booleananswer",
            name="question",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boolean_answer",
                to="assessments.question",
            ),
        ),
    ]
