# Generated by Django 5.2.16 on 2026-08-15 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessments", "0015_alter_booleananswer_question"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="acceptedanswer",
            name="unique_accepted_answer_per_question",
        ),
        migrations.AlterField(
            model_name="acceptedanswer",
            name="question",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accepted_answer",
                to="assessments.question",
            ),
        ),
    ]
