# Generated by Django 5.2.16 on 2026-08-18 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "assessments",
            "0016_remove_acceptedanswer_unique_accepted_answer_per_question_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="acceptedanswer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accepted_answers",
                to="assessments.question",
            ),
        ),
    ]
