# Generated by Django 5.2.16 on 2026-08-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessments", "0017_alter_acceptedanswer_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="instructions",
            field=models.TextField(blank=True, verbose_name="Instructions"),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="max_score",
            field=models.PositiveSmallIntegerField(
                default=100, null=True, verbose_name="Maximum Score"
            ),
        ),
        migrations.AlterField(
            model_name="quizcontent",
            name="max_attempts",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Set to 0 for unlimited attempts.",
                null=True,
                verbose_name="Maximum Attempts",
            ),
        ),
        migrations.AlterField(
            model_name="quizcontent",
            name="passing_score",
            field=models.PositiveSmallIntegerField(
                default=70,
                help_text="Required score (0-100) to pass.",
                null=True,
                verbose_name="Passing Score (%)",
            ),
        ),
    ]
