# Generated by Django 5.2.16 on 2026-09-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessments", "0018_alter_assignment_instructions_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignment",
            name="max_score",
        ),
        migrations.AddField(
            model_name="assignment",
            name="passing_score",
            field=models.PositiveSmallIntegerField(
                default=70,
                help_text="Required score (0-100) to pass.",
                null=True,
                verbose_name="Passing Score",
            ),
        ),
    ]
