# Generated by Django 5.2.16 on 2026-09-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessments", "0019_remove_assignment_max_score_assignment_passing_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="max_score",
            field=models.PositiveSmallIntegerField(
                default=100, null=True, verbose_name="Passing Score"
            ),
        ),
    ]
