# Generated by Django 5.2.16 on 2026-09-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessments", "0020_assignment_max_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizcontent",
            name="max_attempts",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=1,
                help_text="Set to 0 for unlimited attempts.",
                null=True,
                verbose_name="Maximum Attempts",
            ),
        ),
        migrations.AlterField(
            model_name="quizcontent",
            name="passing_score",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=70,
                help_text="Required score (0-100) to pass.",
                null=True,
                verbose_name="Passing Score (%)",
            ),
        ),
    ]
