# Generated by Django 5.2.16 on 2026-09-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailinbox",
            name="subject",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
