# Generated by Django 5.2.16 on 2026-09-03 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landing", "0002_emailinbox_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="sociallink",
            name="contact",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="landing.contact",
            ),
            preserve_default=False,
        ),
    ]
