# Generated by Django 5.2.16 on 2026-09-03 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landing", "0003_sociallink_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featureitem",
            name="feature",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="landing.sitefeature",
            ),
        ),
        migrations.AlterField(
            model_name="highlightedpoint",
            name="highlight",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="endpoints",
                to="landing.sitehighlight",
            ),
        ),
        migrations.AlterField(
            model_name="sociallink",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="social_links",
                to="landing.contact",
            ),
        ),
    ]
