# Generated by Django 5.2.16 on 2026-09-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landing", "0004_alter_featureitem_feature_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="highlightedpoint",
            name="end_point",
            field=models.CharField(),
        ),
    ]
