# Generated by Django 5.2.16 on 2026-09-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landing", "0005_alter_highlightedpoint_end_point"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIEndpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField(default=0)),
            ],
        ),
    ]
