# Generated by Django 5.2.16 on 2026-09-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landing", "0006_apiendpoint"),
    ]

    operations = [
        migrations.CreateModel(
            name="Statistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_endpoints", models.IntegerField(default=0)),
                ("automated_tests", models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name="APIEndpoint",
        ),
    ]
