# Generated by Django 5.2.16 on 2026-09-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landing", "0007_statistics_delete_apiendpoint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featureitem",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="landing/feature/"
            ),
        ),
        migrations.AlterField(
            model_name="statistics",
            name="api_endpoints",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="statistics",
            name="automated_tests",
            field=models.CharField(),
        ),
    ]
