# Generated by Django 5.2.16 on 2026-07-24 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("enrollments", "0005_courseprogress"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_number",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Certificate Number"
                    ),
                ),
                (
                    "verification_code",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="Verification Code"
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Issued At"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="certificates/", verbose_name="Certificate File"
                    ),
                ),
                (
                    "enrollment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate",
                        to="enrollments.enrollment",
                        verbose_name="Enrollment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificate",
                "verbose_name_plural": "Certificates",
                "ordering": ("-issued_at",),
                "indexes": [
                    models.Index(
                        fields=["verification_code"],
                        name="certificate_verific_e033f7_idx",
                    )
                ],
            },
        ),
    ]
