# Generated by Django 5.2.16 on 2026-07-24 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("certificates", "0001_initial"),
        ("courses", "0007_remove_course_instructors_coursecollaborator_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificateTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "version",
                    models.PositiveSmallIntegerField(default=1, verbose_name="Version"),
                ),
                (
                    "background",
                    models.FileField(
                        help_text="Certificate background (PDF or image).",
                        upload_to="certificates/templates/",
                        verbose_name="Background",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate_templates",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificate Template",
                "verbose_name_plural": "Certificate Templates",
                "ordering": ("-is_active", "name", "-version"),
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="certificate_is_acti_4f5823_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "version"),
                        name="unique_certificate_template_version",
                    )
                ],
            },
        ),
    ]
