# Generated by Django 5.2.16 on 2026-09-15 16:36

from django.db import migrations, models

import certificates.models


class Migration(migrations.Migration):
    dependencies = [
        ("certificates", "0002_certificatetemplate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="file",
            field=models.FileField(
                upload_to=certificates.models.file_upload_path,
                verbose_name="Certificate File",
            ),
        ),
    ]
