# Generated by Django 5.2.16 on 2026-07-09 06:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("guest", "Guest"),
                            ("student", "Student"),
                            ("instructor", "Instructor"),
                            ("teaching assistant", "Teaching Assistant"),
                            ("moderator", "Moderator"),
                            ("support agent", "Support Agent"),
                            ("admin", "Admin"),
                        ],
                        max_length=18,
                        verbose_name="Name",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "user",
                    models.ManyToManyField(
                        related_name="roles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
        ),
    ]
