# Generated by Django 5.2.16 on 2026-07-09 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device", models.CharField(max_length=255, verbose_name="Device")),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP Address")),
                ("user_agent", models.TextField(verbose_name="User Agent")),
                ("login_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity_at", models.DateTimeField(auto_now=True)),
                (
                    "is_revoked",
                    models.BooleanField(default=False, verbose_name="Is Revoked"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "ordering": ["-login_at"],
                "indexes": [
                    models.Index(
                        fields=["user"], name="accounts_us_user_id_691a59_idx"
                    ),
                    models.Index(
                        fields=["last_activity_at"],
                        name="accounts_us_last_ac_eb2ee1_idx",
                    ),
                ],
            },
        ),
    ]
