# Generated by Django 5.2.16 on 2026-07-11 11:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_loginhistory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="role",
            name="user",
        ),
        migrations.AddField(
            model_name="role",
            name="users",
            field=models.ManyToManyField(
                related_name="roles", to=settings.AUTH_USER_MODEL, verbose_name="Users"
            ),
        ),
    ]
