# Generated by Django 5.2.16 on 2026-08-25 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_remove_role_user_role_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                choices=[("student", "Student"), ("instructor", "Instructor")],
                max_length=18,
                verbose_name="Name",
            ),
        ),
    ]
