# Generated by Django 5.2.16 on 2026-07-22 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Name")),
                (
                    "slug",
                    models.SlugField(max_length=170, unique=True, verbose_name="Slug"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Display Order"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave empty for a top-level category.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="courses.category",
                        verbose_name="Parent Category",
                    ),
                ),
            ],
            options={
                "ordering": ("display_order", "name"),
                "indexes": [
                    models.Index(
                        fields=["display_order"], name="courses_cat_display_07b7ab_idx"
                    )
                ],
            },
        ),
    ]
