# Generated by Django 5.2.16 on 2026-07-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "slug",
                    models.SlugField(max_length=120, unique=True, verbose_name="Slug"),
                ),
            ],
            options={
                "ordering": ("name",),
                "indexes": [
                    models.Index(fields=["name"], name="courses_tag_name_fabe02_idx")
                ],
            },
        ),
    ]
