# Generated by Django 5.2.16 on 2026-07-22 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_tag"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Subtitle"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=280, unique=True, verbose_name="Slug"),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        upload_to="courses/thumbnails/",
                        verbose_name="Thumbnail",
                    ),
                ),
                (
                    "promotional_video",
                    models.URLField(blank=True, verbose_name="Promotional Video"),
                ),
                (
                    "language",
                    models.CharField(
                        default="English", max_length=50, verbose_name="Language"
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("all_levels", "All Levels"),
                        ],
                        default="all_levels",
                        max_length=20,
                        verbose_name="Level",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("ready_for_review", "Ready for Review"),
                            ("under_review", "Under Review"),
                            ("published", "Published"),
                            ("updated", "Updated"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("private", "Private"),
                            ("unlisted", "Unlisted"),
                        ],
                        default="public",
                        max_length=20,
                        verbose_name="Visibility",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0.0", max_length=20, verbose_name="Version"
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Published At"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="courses",
                        to="courses.category",
                        verbose_name="Category",
                    ),
                ),
                (
                    "instructors",
                    models.ManyToManyField(
                        related_name="teaching_courses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Instructors",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_courses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="courses",
                        to="courses.tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "ordering": ("-published_at", "title"),
                "indexes": [
                    models.Index(fields=["slug"], name="courses_cou_slug_2e551f_idx"),
                    models.Index(
                        fields=["status"], name="courses_cou_status_158bbf_idx"
                    ),
                    models.Index(
                        fields=["category"], name="courses_cou_categor_108713_idx"
                    ),
                    models.Index(
                        fields=["language"], name="courses_cou_languag_94bd99_idx"
                    ),
                    models.Index(
                        fields=["published_at"], name="courses_cou_publish_2f46d3_idx"
                    ),
                ],
            },
        ),
    ]
