# Generated by Django 5.2.16 on 2026-07-22 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_learningoutcome"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prerequisite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=1, verbose_name="Order"),
                ),
                (
                    "description",
                    models.CharField(max_length=500, verbose_name="Description"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prerequisites",
                        to="courses.course",
                        verbose_name="Course",
                    ),
                ),
            ],
            options={
                "ordering": ("course", "order"),
                "indexes": [
                    models.Index(
                        fields=["course", "order"],
                        name="courses_pre_course__b9c3c1_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("course", "order"),
                        name="unique_prerequisite_order_per_course",
                    )
                ],
            },
        ),
    ]
