# Generated by Django 5.2.16 on 2026-07-22 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0006_targetaudience"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="instructors",
        ),
        migrations.CreateModel(
            name="CourseCollaborator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("lead_instructor", "Lead Instructor"),
                            ("instructor", "Instructor"),
                            ("teaching_assistant", "Teaching Assistant"),
                        ],
                        default="instructor",
                        max_length=25,
                        verbose_name="Role",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_collaborators",
                        to="courses.course",
                        verbose_name="Course",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_collaborations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "ordering": ("course", "role", "user__username"),
            },
        ),
        migrations.AddField(
            model_name="course",
            name="collaborators",
            field=models.ManyToManyField(
                related_name="teaching_courses",
                through="courses.CourseCollaborator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Collaborators",
            ),
        ),
        migrations.AddConstraint(
            model_name="coursecollaborator",
            constraint=models.UniqueConstraint(
                fields=("course", "user"), name="unique_course_collaborator"
            ),
        ),
    ]
