# Generated by Django 5.2.16 on 2026-07-25 13:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0007_remove_course_instructors_coursecollaborator_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_trailer",
            field=models.URLField(blank=True, verbose_name="Course Trailer"),
        ),
        migrations.AddField(
            model_name="course",
            name="duration",
            field=models.DurationField(
                blank=True,
                help_text="Estimated duration of this Course.",
                null=True,
                verbose_name="Duration",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="Price"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="price_discount",
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="price_type",
            field=models.CharField(
                choices=[("paid", "Paid"), ("free", "Free")],
                default="free",
                verbose_name="Price Type",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="short_description",
            field=models.CharField(
                blank=True, max_length=280, verbose_name="Short Description"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="version_note",
            field=models.CharField(
                blank=True, max_length=250, verbose_name="Version Note"
            ),
        ),
    ]
