# Generated by Django 5.2.16 on 2026-07-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0009_course_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="seo_description",
            field=models.CharField(
                blank=True, max_length=160, verbose_name="SEO Description"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="seo_keywords",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="SEO keywords"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="seo_title",
            field=models.CharField(blank=True, max_length=60, verbose_name="SEO Title"),
        ),
    ]
