# Generated by Django 5.2.16 on 2026-08-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0010_course_seo_description_course_seo_keywords_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("not_submitted", "Not Submitted"),
                    ("pending", "Pending Review"),
                    ("under_review", "Under Review"),
                    ("approved", "Approved"),
                    ("changes_requested", "Changes Requested"),
                ],
                default="not_submitted",
                help_text="Current position in review workflow",
                max_length=20,
                verbose_name="Review Status",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("updated", "Updated"),
                    ("archived", "Archived"),
                ],
                default="draft",
                help_text="Lifecycle state of the course content",
                max_length=30,
                verbose_name="Status",
            ),
        ),
    ]
