# Generated by Django 5.2.16 on 2026-08-01 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0011_course_review_status_alter_course_status"),
        ("enrollments", "0005_courseprogress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("updated", "Updated"),
                    ("archived", "Archived"),
                ],
                default="draft",
                help_text="Lifecycle state of the course content",
                max_length=30,
                verbose_name="Status",
            ),
        ),
        migrations.CreateModel(
            name="CourseFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.PositiveSmallIntegerField()),
                ("title", models.CharField(blank=True, max_length=150)),
                ("review", models.TextField(blank=True)),
                ("is_public", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enrollment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="enrollments.enrollment",
                        verbose_name="Enrollment",
                    ),
                ),
            ],
        ),
    ]
