# Generated by Django 5.2.16 on 2026-08-01 16:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0012_alter_course_status_coursefeedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("not_submitted", "Not Submitted"),
                    ("pending", "Pending Review"),
                    ("under_review", "Under Review"),
                    ("approved", "Approved"),
                    ("changes_requested", "Changes Requested"),
                    ("rejected", "Rejected"),
                ],
                default="not_submitted",
                help_text="Current position in review workflow",
                max_length=20,
                verbose_name="Review Status",
            ),
        ),
        migrations.AlterField(
            model_name="coursefeedback",
            name="rating",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10000),
                ]
            ),
        ),
    ]
