# Generated by Django 5.2.16 on 2026-08-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0013_alter_course_review_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.CharField(blank=True, max_length=100, verbose_name="Icon"),
        ),
    ]
