# Generated by Django 5.2.16 on 2026-08-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0014_category_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("fa", "Farsi")],
                default="en",
                max_length=2,
                verbose_name="Language",
            ),
        ),
    ]
