# Generated by Django 5.2.16 on 2026-08-08 11:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0017_coursefeature"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coursefeedback",
            old_name="review",
            new_name="comment",
        ),
        migrations.AlterField(
            model_name="coursefeedback",
            name="rating",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
    ]
