# Generated by Django 5.2.16 on 2026-08-08 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0018_rename_review_coursefeedback_comment_and_more"),
        ("enrollments", "0007_alter_lessoncontentprogress_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coursefeedback",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="coursefeedback",
            name="is_public",
        ),
        migrations.RemoveField(
            model_name="coursefeedback",
            name="rating",
        ),
        migrations.RemoveField(
            model_name="coursefeedback",
            name="title",
        ),
        migrations.RemoveField(
            model_name="coursefeedback",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="coursefeedback",
            name="feedback",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback_interactions",
                to="enrollments.enrollment",
                verbose_name="Enrollment",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="coursefeedback",
            name="liked",
            field=models.BooleanField(default=True, verbose_name="Liked"),
        ),
        migrations.AlterField(
            model_name="coursefeedback",
            name="enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="enrollments.enrollment",
                verbose_name="Enrollment",
            ),
        ),
    ]
