# Generated by Django 5.2.16 on 2026-08-08 19:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0019_remove_coursefeedback_comment_and_more"),
        ("enrollments", "0007_alter_lessoncontentprogress_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coursefeedback",
            name="feedback",
        ),
        migrations.RemoveField(
            model_name="coursefeedback",
            name="liked",
        ),
        migrations.AddField(
            model_name="coursefeedback",
            name="comment",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="coursefeedback",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="coursefeedback",
            name="rating",
            field=models.PositiveSmallIntegerField(
                default=2,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="coursefeedback",
            name="title",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="coursefeedback",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="coursefeedback",
            name="enrollment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback",
                to="enrollments.enrollment",
                verbose_name="Enrollment",
            ),
        ),
        migrations.CreateModel(
            name="CourseFeedbackInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("liked", models.BooleanField(default=True, verbose_name="Liked")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="enrollments.enrollment",
                        verbose_name="Enrollment",
                    ),
                ),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_interactions",
                        to="enrollments.enrollment",
                        verbose_name="Enrollment",
                    ),
                ),
            ],
        ),
    ]
