# Generated by Django 5.2.16 on 2026-08-08 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0020_remove_coursefeedback_feedback_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursefeedbackinteraction",
            name="feedback",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback_interactions",
                to="courses.coursefeedback",
                verbose_name="Feedback",
            ),
        ),
    ]
