# Generated by Django 5.2.16 on 2026-08-19 11:38

from django.db import migrations

import utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0021_alter_coursefeedbackinteraction_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningoutcome",
            name="order",
            field=utils.fields.SequentialField(),
        ),
        migrations.AlterField(
            model_name="prerequisite",
            name="order",
            field=utils.fields.SequentialField(),
        ),
        migrations.AlterField(
            model_name="targetaudience",
            name="order",
            field=utils.fields.SequentialField(),
        ),
    ]
