# Generated by Django 5.2.16 on 2026-08-20 13:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "courses",
            "0022_alter_learningoutcome_order_alter_prerequisite_order_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="prerequisite",
            name="unique_prerequisite_order_per_course",
        ),
        migrations.RemoveConstraint(
            model_name="targetaudience",
            name="unique_target_audience_order_per_course",
        ),
    ]
