# Generated by Django 5.2.16 on 2026-08-23 15:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "courses",
            "0023_remove_prerequisite_unique_prerequisite_order_per_course_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="courses",
                to="courses.category",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="course",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[("en", "English"), ("fa", "Farsi")],
                default="en",
                max_length=2,
                verbose_name="Language",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                    ("all_levels", "All Levels"),
                ],
                default="all_levels",
                max_length=20,
                verbose_name="Level",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                null=True,
                verbose_name="Price",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="price_discount",
            field=models.PositiveSmallIntegerField(
                default=0,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="price_type",
            field=models.CharField(
                blank=True,
                choices=[("paid", "Paid"), ("free", "Free")],
                default="free",
                verbose_name="Price Type",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="courses/thumbnails/",
                verbose_name="Thumbnail",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="version",
            field=models.CharField(
                blank=True, default="1.0.0", max_length=20, verbose_name="Version"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="visibility",
            field=models.CharField(
                blank=True,
                choices=[
                    ("public", "Public"),
                    ("private", "Private"),
                    ("unlisted", "Unlisted"),
                ],
                default="public",
                max_length=20,
                verbose_name="Visibility",
            ),
        ),
    ]
