# Generated by Django 5.2.16 on 2026-08-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0024_alter_course_category_alter_course_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("updated", "Updated"),
                    ("archived", "Archived"),
                    ("submitted", "Submitted"),
                ],
                default="draft",
                help_text="Lifecycle state of the course content",
                max_length=30,
                verbose_name="Status",
            ),
        ),
    ]
