# Generated by Django 5.2.16 on 2026-09-09 07:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0025_alter_course_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="collaborators",
        ),
    ]
