# Generated by Django 5.2.16 on 2026-09-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0026_remove_course_collaborators"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                max_digits=10,
                null=True,
                verbose_name="Price",
            ),
        ),
        migrations.DeleteModel(
            name="CourseCollaborator",
        ),
    ]
