# Generated by Django 5.2.16 on 2026-07-23 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0007_remove_course_instructors_coursecollaborator_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=1, verbose_name="Order"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Published"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="courses.course",
                        verbose_name="Course",
                    ),
                ),
            ],
            options={
                "ordering": ("course", "order"),
                "indexes": [
                    models.Index(
                        fields=["course"], name="curriculums_course__c3f403_idx"
                    ),
                    models.Index(fields=["order"], name="curriculums_order_7d49f0_idx"),
                    models.Index(
                        fields=["course", "order"],
                        name="curriculums_course__f51e1a_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("course", "order"),
                        name="unique_section_order_per_course",
                    )
                ],
            },
        ),
    ]
