# Generated by Django 5.2.16 on 2026-07-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculums", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="estimated_duration",
            field=models.DurationField(
                blank=True,
                help_text="Estimated time to complete this section.",
                null=True,
                verbose_name="Estimated Duration",
            ),
        ),
    ]
