# Generated by Django 5.2.16 on 2026-07-23 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculums", "0002_section_estimated_duration"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("slug", models.SlugField(max_length=280, verbose_name="Slug")),
                (
                    "lesson_type",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("article", "Article"),
                            ("file", "File"),
                            ("quiz", "Quiz"),
                            ("assignment", "Assignment"),
                            ("live_session", "Live Session"),
                            ("coding_exercise", "Coding Exercise"),
                        ],
                        max_length=30,
                        verbose_name="Type",
                    ),
                ),
                (
                    "duration",
                    models.DurationField(
                        blank=True,
                        help_text="Estimated duration of this lesson.",
                        null=True,
                        verbose_name="Duration",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=1, verbose_name="Order"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Published"),
                ),
                (
                    "is_preview",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this lesson is accessible without enrollment.",
                        verbose_name="Preview Enabled",
                    ),
                ),
                (
                    "completion_criteria",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("watch_video", "Watch Video"),
                            ("read_article", "Read Article"),
                            ("pass_quiz", "Pass Quiz"),
                            ("submit_assignment", "Submit Assignment"),
                        ],
                        default="manual",
                        max_length=30,
                        verbose_name="Completion Criteria",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="curriculums.section",
                        verbose_name="Section",
                    ),
                ),
            ],
            options={
                "ordering": ("section", "order"),
                "indexes": [
                    models.Index(
                        fields=["section"], name="curriculums_section_3289d1_idx"
                    ),
                    models.Index(
                        fields=["lesson_type"], name="curriculums_lesson__c01d5e_idx"
                    ),
                    models.Index(
                        fields=["is_published"], name="curriculums_is_publ_2b0845_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("section", "order"),
                        name="unique_lesson_order_per_section",
                    )
                ],
            },
        ),
    ]
