# Generated by Django 5.2.16 on 2026-07-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculums", "0003_lesson"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="lesson_type",
            field=models.CharField(
                choices=[
                    ("video", "Video"),
                    ("article", "Article"),
                    ("file", "File"),
                    ("quiz", "Quiz"),
                    ("assignment", "Assignment"),
                    ("live_session", "Live Session"),
                    ("coding_exercise", "Coding Exercise"),
                    ("external_resource", "External Resource"),
                ],
                max_length=30,
                verbose_name="Type",
            ),
        ),
    ]
