# Generated by Django 5.2.16 on 2026-07-23 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculums", "0004_alter_lesson_lesson_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("article", "Article"),
                            ("file", "File"),
                            ("quiz", "Quiz"),
                            ("assignment", "Assignment"),
                            ("live_session", "Live Session"),
                            ("coding_exercise", "Coding Exercise"),
                        ],
                        max_length=30,
                        verbose_name="Content Type",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(verbose_name="Order")),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Published"),
                ),
            ],
            options={
                "ordering": ("lesson", "order"),
            },
        ),
        migrations.CreateModel(
            name="VideoContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("file", "Uploaded File"), ("url", "External URL")],
                        default="file",
                        max_length=20,
                    ),
                ),
                (
                    "uploaded_video",
                    models.FileField(blank=True, upload_to="courses/videos/"),
                ),
                ("external_url", models.URLField(blank=True)),
                ("duration", models.DurationField(blank=True, null=True)),
                ("transcript", models.TextField(blank=True)),
                (
                    "captions",
                    models.FileField(blank=True, upload_to="courses/captions/"),
                ),
            ],
            options={
                "verbose_name": "Video Content",
                "verbose_name_plural": "Video Contents",
            },
        ),
        migrations.RemoveIndex(
            model_name="lesson",
            name="curriculums_lesson__c01d5e_idx",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="lesson_type",
        ),
        migrations.AddField(
            model_name="lessoncontent",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contents",
                to="curriculums.lesson",
                verbose_name="Lesson",
            ),
        ),
        migrations.AddField(
            model_name="videocontent",
            name="content",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="video",
                to="curriculums.lessoncontent",
            ),
        ),
        migrations.AddConstraint(
            model_name="lessoncontent",
            constraint=models.UniqueConstraint(
                fields=("lesson", "order"), name="unique_content_order_per_lesson"
            ),
        ),
    ]
