# Generated by Django 5.2.16 on 2026-07-24 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculums", "0005_lessoncontent_videocontent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="courses/files/", verbose_name="File"),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="Optional name shown to learners instead of the filename.",
                        max_length=255,
                        verbose_name="Display Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "is_downloadable",
                    models.BooleanField(default=True, verbose_name="Downloadable"),
                ),
                (
                    "file_size",
                    models.PositiveBigIntegerField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="File Size (bytes)",
                    ),
                ),
                (
                    "content",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file",
                        to="curriculums.lessoncontent",
                        verbose_name="Lesson Content",
                    ),
                ),
            ],
            options={
                "verbose_name": "File Content",
                "verbose_name_plural": "File Contents",
            },
        ),
    ]
