# Generated by Django 5.2.16 on 2026-07-24 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculums", "0006_filecontent"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="The article content in Markdown or HTML format.",
                        verbose_name="Body",
                    ),
                ),
                (
                    "estimated_read_time",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Estimated reading time in minutes.",
                        null=True,
                        verbose_name="Estimated Read Time",
                    ),
                ),
                (
                    "content",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="article",
                        to="curriculums.lessoncontent",
                        verbose_name="Lesson Content",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article Content",
                "verbose_name_plural": "Article Contents",
            },
        ),
    ]
