# Generated by Django 5.2.16 on 2026-07-24 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculums", "0007_articlecontent"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "instructions",
                    models.TextField(blank=True, verbose_name="Instructions"),
                ),
                (
                    "passing_score",
                    models.PositiveSmallIntegerField(
                        default=70,
                        help_text="Required score (0-100) to pass.",
                        verbose_name="Passing Score (%)",
                    ),
                ),
                (
                    "time_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Leave empty for unlimited time.",
                        null=True,
                        verbose_name="Time Limit (minutes)",
                    ),
                ),
                (
                    "max_attempts",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Set to 0 for unlimited attempts.",
                        verbose_name="Maximum Attempts",
                    ),
                ),
                (
                    "shuffle_questions",
                    models.BooleanField(
                        default=False, verbose_name="Shuffle Questions"
                    ),
                ),
                (
                    "shuffle_choices",
                    models.BooleanField(default=False, verbose_name="Shuffle Choices"),
                ),
                (
                    "show_correct_answers",
                    models.BooleanField(
                        default=True, verbose_name="Show Correct Answers"
                    ),
                ),
                (
                    "content",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz",
                        to="curriculums.lessoncontent",
                        verbose_name="Lesson Content",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz Content",
                "verbose_name_plural": "Quiz Contents",
            },
        ),
    ]
