# Generated by Django 5.2.16 on 2026-07-24 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculums", "0008_quizcontent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("single_choice", "Single Choice"),
                            ("multiple_choice", "Multiple Choice"),
                            ("true_false", "True / False"),
                            ("short_answer", "Short Answer"),
                        ],
                        default="single_choice",
                        max_length=30,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField()),
                ("points", models.PositiveSmallIntegerField(default=1)),
                ("explanation", models.TextField(blank=True)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="curriculums.quizcontent",
                    ),
                ),
            ],
        ),
    ]
