# Generated by Django 5.2.16 on 2026-07-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculums", "0009_question"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ("order",)},
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["quiz"], name="curriculums_quiz_id_88bc85_idx"),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["order"], name="curriculums_order_afbf27_idx"),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.UniqueConstraint(
                fields=("quiz", "order"), name="unique_question_order_per_quiz"
            ),
        ),
    ]
