# Generated by Django 5.2.16 on 2026-07-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculums", "0011_acceptedanswer_choice"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="acceptedanswer",
            constraint=models.UniqueConstraint(
                fields=("question", "answer"),
                name="unique_accepted_answer_per_question",
            ),
        ),
    ]
