# Generated by Django 5.2.16 on 2026-07-24 17:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("curriculums", "0012_acceptedanswer_unique_accepted_answer_per_question"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="choice",
            options={},
        ),
        migrations.RemoveConstraint(
            model_name="acceptedanswer",
            name="unique_accepted_answer_per_question",
        ),
        migrations.RemoveConstraint(
            model_name="choice",
            name="unique_choice_order_per_question",
        ),
        migrations.RemoveField(
            model_name="acceptedanswer",
            name="question",
        ),
        migrations.RemoveField(
            model_name="choice",
            name="question",
        ),
    ]
