# Generated by Django 5.2.16 on 2026-07-24 17:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("curriculums", "0013_alter_choice_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AcceptedAnswer",
        ),
        migrations.DeleteModel(
            name="Choice",
        ),
        migrations.RemoveField(
            model_name="quizcontent",
            name="content",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
        migrations.DeleteModel(
            name="QuizContent",
        ),
    ]
