# Generated by Django 5.2.16 on 2026-07-27 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculums", "0014_delete_acceptedanswer_delete_choice_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="videocontent",
            old_name="uploaded_video",
            new_name="video_file",
        ),
        migrations.RemoveField(
            model_name="videocontent",
            name="captions",
        ),
        migrations.AddField(
            model_name="lesson",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.CreateModel(
            name="VideoCaption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(max_length=10)),
                ("label", models.CharField(blank=True, max_length=50)),
                ("file", models.FileField(upload_to="courses/captions/")),
                (
                    "file_format",
                    models.CharField(
                        choices=[("vtt", "WebVTT"), ("srt", "SubRip")], max_length=10
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="captions",
                        to="curriculums.videocontent",
                    ),
                ),
            ],
        ),
    ]
