# Generated by Django 5.2.16 on 2026-07-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculums", "0015_rename_uploaded_video_videocontent_video_file_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="videocaption",
            constraint=models.UniqueConstraint(
                fields=("video", "language"), name="unique_caption_language_per_video"
            ),
        ),
        migrations.AddConstraint(
            model_name="videocaption",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("video",),
                name="unique_default_caption_per_video",
            ),
        ),
    ]
