# Generated by Django 5.2.16 on 2026-07-27 19:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("curriculums", "0016_videocaption_unique_caption_language_per_video_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="section",
            old_name="estimated_duration",
            new_name="duration",
        ),
    ]
