# Generated by Django 5.2.16 on 2026-07-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculums", "0017_rename_estimated_duration_section_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="filecontent",
            name="file_url",
            field=models.URLField(blank=True),
        ),
    ]
