# Generated by Django 5.2.16 on 2026-07-28 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("curriculums", "0018_filecontent_file_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "file",
                    models.FileField(upload_to="courses/files/", verbose_name="File"),
                ),
                ("file_url", models.URLField(blank=True)),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="Optional name shown to learners instead of the filename.",
                        max_length=255,
                        verbose_name="Display Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "is_downloadable",
                    models.BooleanField(default=True, verbose_name="Downloadable"),
                ),
                (
                    "file_size",
                    models.PositiveBigIntegerField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="File Size (bytes)",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
    ]
