# Generated by Django 5.2.16 on 2026-07-28 09:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import curriculums.models.attachment


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0008_course_course_trailer_course_duration_course_price_and_more"),
        ("curriculums", "0019_attachment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attachment",
            options={
                "ordering": ("title", "created_at"),
                "verbose_name": "Attachment",
                "verbose_name_plural": "Attachments",
            },
        ),
        migrations.RemoveField(
            model_name="attachment",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="attachment",
            name="display_name",
        ),
        migrations.RemoveField(
            model_name="attachment",
            name="object_id",
        ),
        migrations.AddField(
            model_name="attachment",
            name="course",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="courses.course",
                verbose_name="Course",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="attachment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Created At",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="attachment",
            name="lesson_content",
            field=models.ForeignKey(
                blank=True,
                help_text="Leave empty if this is a course-level attachment.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="curriculums.lessoncontent",
                verbose_name="Lesson Content",
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="title",
            field=models.CharField(
                default="file",
                help_text="Name displayed to learners.",
                max_length=255,
                verbose_name="Title",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="attachment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="file",
            field=models.FileField(
                blank=True,
                upload_to=curriculums.models.attachment.attachment_upload_path,
                verbose_name="File",
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="file_url",
            field=models.URLField(blank=True, verbose_name="External URL"),
        ),
        migrations.AddIndex(
            model_name="attachment",
            index=models.Index(
                fields=["course"], name="curriculums_course__93e20c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attachment",
            index=models.Index(
                fields=["lesson_content"], name="curriculums_lesson__faf364_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attachment",
            index=models.Index(
                fields=["is_downloadable"], name="curriculums_is_down_2e572f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="attachment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("file__gt", ""), ("file_url", "")),
                    models.Q(("file", ""), ("file_url__gt", "")),
                    _connector="OR",
                ),
                name="attachment_exactly_one_source",
            ),
        ),
    ]
