# Generated by Django 5.2.16 on 2026-07-29 12:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("curriculums", "0020_alter_attachment_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lessoncontent",
            name="is_published",
        ),
    ]
