# Generated by Django 5.2.16 on 2026-07-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculums", "0021_remove_lessoncontent_is_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="videocontent",
            name="text",
            field=models.TextField(blank=True, verbose_name="Text"),
        ),
    ]
