# Generated by Django 5.2.16 on 2026-07-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculums", "0022_videocontent_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Name displayed to learners.",
                max_length=255,
                verbose_name="Title",
            ),
        ),
    ]
