# Generated by Django 5.2.16 on 2026-08-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculums", "0023_alter_attachment_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessoncontent",
            name="is_main_content",
            field=models.BooleanField(default=False),
        ),
    ]
