# Generated by Django 5.2.16 on 2026-08-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculums", "0024_lessoncontent_is_main_content"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="lessoncontent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_main_content", True)),
                fields=("lesson",),
                name="unique_main_content_per_lesson",
            ),
        ),
    ]
