# Generated by Django 5.2.16 on 2026-08-10 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculums", "0025_lessoncontent_unique_main_content_per_lesson"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="completion_criteria",
        ),
        migrations.CreateModel(
            name="LessonCompletionCriteria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criteria_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("watch_video", "Watch Video"),
                            ("read_article", "Read Article"),
                            ("pass_quiz", "Pass Quiz"),
                            ("submit_assignment", "Submit Assignment"),
                        ],
                        default="manual",
                        max_length=30,
                        verbose_name="Criteria Type",
                    ),
                ),
                (
                    "video_watch_percentage",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Required percentage of video to watch (1-100).",
                        null=True,
                        verbose_name="Video Watch Percentage",
                    ),
                ),
                (
                    "quiz_passing_score",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Minimum score to pass the quiz.",
                        null=True,
                        verbose_name="Quiz Passing Score",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lesson",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completion_criteria",
                        to="curriculums.lesson",
                        verbose_name="Lesson",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lesson Completion Criteria",
                "verbose_name_plural": "Lesson Completion Criteria",
            },
        ),
    ]
