# Generated by Django 5.2.16 on 2026-08-20 13:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("curriculums", "0026_remove_lesson_completion_criteria_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="lesson",
            name="unique_lesson_order_per_section",
        ),
        migrations.RemoveConstraint(
            model_name="section",
            name="unique_section_order_per_course",
        ),
    ]
