# Generated by Django 5.2.16 on 2026-08-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculums", "0027_remove_lesson_unique_lesson_order_per_section_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filecontent",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="courses/files/", verbose_name="File"
            ),
        ),
    ]
