# Generated by Django 5.2.16 on 2026-08-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculums", "0028_alter_filecontent_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videocontent",
            name="video_file",
            field=models.FileField(blank=True, null=True, upload_to="courses/videos/"),
        ),
    ]
