# Generated by Django 5.2.16 on 2026-08-23 15:22

from django.db import migrations, models

import curriculums.models.attachment


class Migration(migrations.Migration):
    dependencies = [
        ("curriculums", "0029_alter_videocontent_video_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlecontent",
            name="body",
            field=models.TextField(
                blank=True,
                help_text="The article content in Markdown or HTML format.",
                verbose_name="Body",
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=curriculums.models.attachment.attachment_upload_path,
                verbose_name="File",
            ),
        ),
    ]
