# Generated by Django 5.2.16 on 2026-09-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculums", "0030_alter_articlecontent_body_alter_attachment_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessoncontent",
            name="is_main_content",
            field=models.BooleanField(default=True),
        ),
    ]
