# Generated by Django 5.2.16 on 2026-09-06 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculums", "0031_alter_lessoncontent_is_main_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessoncontent",
            name="lesson",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content",
                to="curriculums.lesson",
                verbose_name="Lesson",
            ),
        ),
    ]
