# Generated by Django 5.2.16 on 2026-09-09 21:12

from django.db import migrations, models

import curriculums.models.file_content
import curriculums.models.video_content


class Migration(migrations.Migration):
    dependencies = [
        ("curriculums", "0032_alter_lessoncontent_lesson"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filecontent",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=curriculums.models.file_content.file_upload_path,
                verbose_name="File",
            ),
        ),
        migrations.AlterField(
            model_name="videocaption",
            name="file",
            field=models.FileField(
                upload_to=curriculums.models.video_content.caption_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="videocontent",
            name="video_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=curriculums.models.video_content.video_upload_path,
            ),
        ),
    ]
